apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "holdit-devops.fullname" . }}
  labels:
    {{- include "holdit-devops.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # 如果需要去除 /rpc 前缀，添加以下注解
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: /rpc
        pathType: Prefix
        backend:
          service:
            name: {{ include "holdit-devops.fullname" . }}
            port:
              number: {{ .Values.service.port }}
