apiVersion: v1
kind: Service
metadata:
  name: {{ include "holdit-devops.fullname" . }}-mongodb
  labels:
    {{- include "holdit-devops.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.config.mongodb.port }}
      targetPort: {{ .Values.config.mongodb.port }}
      protocol: TCP
      name: mongodb
  selector:
    app: {{ include "holdit-devops.fullname" . }}-mongodb
