{{- if .Values.config.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "holdit-devops.fullname" . }}-mongodb
  labels:
    {{- include "holdit-devops.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "holdit-devops.fullname" . }}-mongodb
  template:
    metadata:
      labels:
        app: {{ include "holdit-devops.fullname" . }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.config.mongodb.image.repository }}:{{ .Values.config.mongodb.image.tag }}"
        ports:
        - containerPort: {{ .Values.config.mongodb.port }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: {{ include "holdit-devops.fullname" . }}-mongodb-pvc
{{- end }}
